'use client'
import React, { useEffect } from 'react';

export const TermsPage: React.FC = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="container animate-enter" style={{ maxWidth: '800px', margin: '0 auto', padding: '2rem 1rem' }}>
      <h1 className="text-gradient" style={{ marginBottom: '2rem' }}>Terms of Service</h1>
      
      <div className="glass-panel" style={{ padding: '2rem' }}>
        <p style={{ marginBottom: '1rem' }}><strong>Last Updated: {new Date().toLocaleDateString()}</strong></p>

        <h2 style={{ fontSize: '1.5rem', marginTop: '2rem', marginBottom: '1rem', color: 'var(--text-primary)' }}>1. Acceptance of Terms</h2>
        <p style={{ marginBottom: '1rem', color: 'var(--text-secondary)' }}>
          By accessing and using Legal Policy Generator (the "Service"), you accept and agree to be bound by the terms and provision of this agreement.
        </p>

        <h2 style={{ fontSize: '1.5rem', marginTop: '2rem', marginBottom: '1rem', color: 'var(--text-primary)' }}>2. Disclaimer of Legal Advice</h2>
        <p style={{ marginBottom: '1rem', color: 'var(--text-secondary)' }}>
          <strong>The documents generated by this Service are for informational purposes only and do not constitute legal advice.</strong> We are not a law firm and are not a substitute for an attorney or law firm. We cannot guarantee that the policies generated will be suitable for your specific needs or that they will comply with all applicable laws in your jurisdiction. You should consult with a qualified attorney to review your legal documents.
        </p>

        <h2 style={{ fontSize: '1.5rem', marginTop: '2rem', marginBottom: '1rem', color: 'var(--text-primary)' }}>3. Use of Service</h2>
        <p style={{ marginBottom: '1rem', color: 'var(--text-secondary)' }}>
          You agree to use the Service only for lawful purposes. You are prohibited from using the Service to generate misleading, fraudulent, or illegal content.
        </p>

        <h2 style={{ fontSize: '1.5rem', marginTop: '2rem', marginBottom: '1rem', color: 'var(--text-primary)' }}>4. Limitation of Liability</h2>
        <p style={{ marginBottom: '1rem', color: 'var(--text-secondary)' }}>
          To the fullest extent permitted by law, Legal Policy Generator shall not be liable for any indirect, incidental, special, consequential or punitive damages, or any loss of profits or revenues.
        </p>

        <h2 style={{ fontSize: '1.5rem', marginTop: '2rem', marginBottom: '1rem', color: 'var(--text-primary)' }}>5. Modifications</h2>
        <p style={{ marginBottom: '1rem', color: 'var(--text-secondary)' }}>
          We reserve the right to modify or replace these Terms at any time. Your continued use of the Service after any such changes constitutes your acceptance of the new Terms.
        </p>
      </div>
    </div>
  );
};
